### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by odow** [odow/StochDualDynamicProgram.jl#17]
This issue is to collate various extensions that we have talked about including in the SDDP algorithm so we can remember them.
- [x] easy AR(n) process
- [ ] when simulating out-of-sample, resolve SDDP to convergence before taking each action
- [x] interpolated SDDP
- [x] Zou, Ahmed, Sun binary variable paper
- [ ] State-dependent risk
- [x] fix nested CVar risk measure. Weighting on CVar is not correct. 
- [x] better parallelisation
- [ ] "SDDP Presolve" automatic rescaling of problems to avoid numerical issues
- [x] set time limits for stage problem solves. Switch to backup solver if exceeds.
- [ ] add cuts with `MathProgBase.addconstr!` which will be faster and reduce memory consumption https://github.com/JuliaOpt/JuMP.jl/issues/969
